title: Percy's URL Shortener
description: This is Percy's personal URL shortener.
logo: /assets/img/logo.png
show_downloads: false
google_analytics: G-621XRQ65MF
theme: jekyll-theme-minimal

permalink: /:slug/

plugins:
  - jekyll-redirect-from

